image:
  repository: ghcr.io/ctchen222/furfriend-finder
  tag: 5a609d3d5cc40f9007f9dd873c7648b53e661bd4

ingress:
  enabled: true
  host: furfriend-finder.com
  className: traefik
  tls:
    enabled: true
    secretName: furfriend-finder-tls
    clusterIssuer: letsencrypt-production

config:
  appBaseUrl: https://furfriend-finder.com
  frontendUrl: https://furfriend-finder.com
  emailVerifyCallbackUrl: https://furfriend-finder.com/verify-email
  corsAllowedOrigins: https://furfriend-finder.com
  telemetry:
    disabled: "false"
    serviceName: furfriend-finder
    otlpEndpoint: "http://otel-collector.observability:4317"

secrets:
  appSecretName: furfriend-finder-app-secret

postgresql:
  secretName: furfriend-finder-postgres-secret
  storage:
    storageClassName: "local-path"
    size: 10Gi

backup:
  hostPath: /var/backups/furfriend-finder/postgres
