apiVersion: v1
kind: Service
metadata:
  name: {{ include "observability-stack.otelCollector.name" . }}
  labels:
    {{- include "observability-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: otel-collector
spec:
  type: ClusterIP
  selector:
    {{- include "observability-stack.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: otel-collector
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: otlp-grpc
    - name: otlp-http
      port: 4318
      targetPort: otlp-http
    - name: prometheus
      port: 8889
      targetPort: prometheus
