apiVersion: v1
kind: Service
metadata:
  name: {{ include "observability-stack.grafana.name" . }}
  labels:
    {{- include "observability-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
spec:
  type: ClusterIP
  selector:
    {{- include "observability-stack.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
  ports:
    - name: http
      port: 3000
      targetPort: http
