apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "observability-stack.grafana.name" . }}-datasources
  labels:
    {{- include "observability-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: grafana
data:
{{ (.Files.Glob "files/grafana/provisioning/datasources/*").AsConfig | indent 2 }}
