apiVersion: v1
kind: Service
metadata:
  name: {{ include "observability-stack.loki.name" . }}
  labels:
    {{- include "observability-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: loki
spec:
  type: ClusterIP
  selector:
    {{- include "observability-stack.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: loki
  ports:
    - name: http
      port: 3100
      targetPort: http
