apiVersion: v1
kind: Service
metadata:
  name: {{ include "observability-stack.prometheus.name" . }}
  labels:
    {{- include "observability-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
spec:
  type: ClusterIP
  selector:
    {{- include "observability-stack.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
  ports:
    - name: http
      port: 9090
      targetPort: http
