apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "observability-stack.prometheus.name" . }}-config
  labels:
    {{- include "observability-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: prometheus
data:
  prometheus.yml: |
{{ .Files.Get "files/prometheus.yml" | indent 4 }}
