apiVersion: v1
kind: Service
metadata:
  name: {{ include "observability-stack.tempo.name" . }}
  labels:
    {{- include "observability-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: tempo
spec:
  type: ClusterIP
  selector:
    {{- include "observability-stack.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: tempo
  ports:
    - name: http
      port: 3200
      targetPort: http
    - name: otlp-grpc
      port: 4317
      targetPort: otlp-grpc
