apiVersion: v1
kind: Secret
metadata:
    name: furfriend-grafana-admin
    namespace: observability
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:ClZWv14=,iv:PKS9mqL2jPx5lYB45F7n7h10EwihO97hNvX1yRPlvPM=,tag:NAvFiamNSlJ2jTUOkyu9sg==,type:str]
    admin-password: ENC[AES256_GCM,data:D/co1A6UpXCIZkm8wQfufCLhe9K2khbteLgkxPCVcvx4C9LkeOiYklcbbict6D7Y,iv:kC5LXokk+omyobxf/t4kgVIQn+DSzS7QKL2rXs+MQ3c=,tag:WwBU9Jx+BjGjKBKiDsT21A==,type:str]
sops:
    age:
        - recipient: age1nvhxw9qgra4xuvluqkz3etedv523w7rx632wyh6w3xsc6uh84cps0h0jka
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVUk9kd3hTbVdRNXdTMWFB
            c1pJTHRiMkxHeDE5MXo5OFRvdzVHaFQ3N2lZCjVzZzR3dVRMLzZoWWU2UGFJL0pY
            bUVQVklZajJFS2tIUkc4eFY1cnJVT28KLS0tIEVtTXNuWTl1eTNMVFJsQnpVZHZy
            RlFvaC81NngrYXdja3BCbzFnQjVRbzgKZeN5KuY9nVeN8UtZtiM0JHYSTNoNApYx
            i97cog0S933r1cPnKHcbmQEN9KxSmsplcqEVwe9mAD8bGBSmS/QSKA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-20T12:32:55Z"
    mac: ENC[AES256_GCM,data:/cY4NrmWor+pm+0d9/CLtjiFgjA0RNgmgz4t4uGFGSq+3DNf06BbFynF+d7pWUpb7zsxg6i1SPsPh3p34PGlbKEYuw9o9Fqu+GnwuvcckBMMjL/EsZF4UHBci6PRxlPazUtdEwr5M5nLaLdr3vwcf/9LloKjmeRXAzoQVIV/5zA=,iv:96Cl273oY4+jlCKvkG78aKaNcRtiUrpDS4jbpoOYzME=,tag:rRdbFXbLkeIfAD9jV2PmPQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
