apiVersion: v1
kind: Namespace
metadata:
  name: furfriend-finder
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
---
apiVersion: v1
kind: Namespace
metadata:
  name: observability
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
