apiVersion: v1
kind: Secret
metadata:
    name: furfriend-finder-app-secret
    namespace: furfriend-finder
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:DjxgAwhhLVlREfwG7FGagL51HvLqOBXZAeYGBH4xH26Is7KC9c6lzSgtAo1rLexacDCFyRhmQdHtvV/r/2t3uvDrDlBM+rnoH4C+HcTkId6XXd88IJYEXw==,iv:G4lGgBo4lsyizonBK39+jMx9rygZkYLmV9iNei2uR6s=,tag:ugREKLK3PFoj8Sst00KNeQ==,type:str]
    GEOCODING_API_KEY: ENC[AES256_GCM,data:be03HS1ZPUbnU8QXBudXSL9yWHc8fIzFosGyVC3SvtE8IMCfo33f,iv:oj8d5V0mIgF/NOH9w/2oSSdE+Iv5BKFce2eCSibikwk=,tag:HyJ9idB0EbWNknLdbLckXg==,type:str]
    CHANNEL_SECRET: ENC[AES256_GCM,data:mPvcOEaC1puhQnFyRQnzDvsmHkpkpGx0ad8A/jwOk90=,iv:pETOwqzpbrYYBpDs/n67DRSdn456KycfW0IPYPQB4rQ=,tag:GxFxeccYBvReKituwjEA3w==,type:str]
    CHANNEL_ACCESS_TOKEN: ENC[AES256_GCM,data:Bs3kBZVFwlSxfWBlIS0AB8TVQqmaUXbKEV+qUUX2Xq3nrQU5i+mBFa/xuoeDtJGlcvqQf8qYqmwY2POz1Xf8P02EQTw/GmLdM9V358WSgRidpmu6qeBVv34WMt8H1yzVGK07SooM1djp7+S503NZ3MGcYjpDNQg6XjguJyMK3TtMSxJPD1px8tYmDD58Vge5PuC6ThIch/cETwX65KHTSnBdGLRwD+9vSjxi6w==,iv:RgXAL7GGaIuMS5NvsLynJJvEq6qY/EdtzO35sP/XYyY=,tag:lxVky3DuutLxSyYqZQp7Ng==,type:str]
    ADMIN_API_KEY: ENC[AES256_GCM,data:fJxyqGBpHnD1TyjxHFuiL+TtSPQAyUl9gB820QXirwE=,iv:s/l/9GgYAF775afT8mdA5fvCwGYp+MMgyrAw+97ab1s=,tag:YFKC6CA/gk1xeRJ8vmWU+Q==,type:str]
    SMTP_HOST: ENC[AES256_GCM,data:T3/gPzWwz9vLVVmqxe1+29AD7zM=,iv:9mJOZA7tu8LQ5xbfxfmQInm5IhiGhEThrmmr2tK6jtk=,tag:/Qi3G4zjmoOXFWdzURhlKA==,type:str]
    SMTP_PORT: ENC[AES256_GCM,data:1lJE,iv:rZNtRZBKC73YwAvRlHRsW89dn5xBOU4teC1muc+lJoI=,tag:9PaJDJzYQqgZbaur42E+Rw==,type:str]
    SMTP_SECURE: ENC[AES256_GCM,data:krQ0Iog=,iv:761RD6vWtdsW2X39LPcKQTLMINhMIpp/pum5+YcnmII=,tag:Ft1MkMqm4YqCsO1HoBz8wQ==,type:str]
    SMTP_USER: ENC[AES256_GCM,data:itGrbEluYnTcvHLMWyBHyFE7HVX90a0e,iv:qG5+Mqq/rAM2ycKHaV9YrQkNr6tABy0FUnZvZgPda3Q=,tag:bZrCEWzbmQ3DVsYnywXNsQ==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:iEh+ydFX9T1+4nDxE0DfxA==,iv:jAoFZ2wkbEPOzEiRHLVH9akOOYRxOrj9PMGfc+RoU0g=,tag:ihgjbVTnIO4mnOqM7AUKkg==,type:str]
    SMTP_SENT_FROM: ENC[AES256_GCM,data:Q4+ef2PvIpZZfKmxYg90Mh2QRSKnCMF3qz4EVQ==,iv:H96dtl/Al9T+HmCA4yieMnEG3VjIM9g5NIExm2OC80E=,tag:yFwubqfQVt/Yqw4LVxIo+w==,type:str]
sops:
    age:
        - recipient: age1nvhxw9qgra4xuvluqkz3etedv523w7rx632wyh6w3xsc6uh84cps0h0jka
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOckZYVDVyN2ZQUkhWYkFW
            N2xrU2xKenhqWVlaOWxuNXBGZ0k0cDJTTVZ3CmlQR2dkUFV1Nk5TNi9kakgrRytn
            cWVHWHNrS0x0a2pGU3BvWXBYandWY2sKLS0tIE9BZW1WTy9HTkdnQlVhWXlXTXJt
            V1VOcWVMVDh5aXJnZC9xKytMNkZzcDAK8IK+Bu1RZkiXzzslSRLG+VU2/EsZD8Kv
            8iCg1nhnHPoM07Ab0lGE7EOm7U3tbSsP/Y5Y465HQVpg3/CR3MbrWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-03T12:56:26Z"
    mac: ENC[AES256_GCM,data:YwlmkScmflZL8YNb/NJbCZpfo9HXM7D1lGzIZcNu9Pk/TLbBBn4mwAKeltucrqkhtSMPBy96972oIbkcwh4OebfDZp7gCWEEldOeKKnSPaL6qrKqdrMdvCTp2oAY4QEJscM/mwxxo7GoGEqrAh71jfYtqnX5R/FnpfDPLAcFMMs=,iv:WBHV0IAuMEk4/McovjPcN7bN01V982IjO2qb8wlrjog=,tag:9nguYBfGFKm1s5YGQUVsOA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
    name: furfriend-finder-postgres-secret
    namespace: furfriend-finder
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:vzOJCBn4QGDppZaX2CGX0jU=,iv:tiFPrRPZqx+jGaXu1lRKpWCIhNQ24qdNCykd3Ml4FB4=,tag:qRUQvyOOUFl2zeG41e4aKw==,type:str]
sops:
    age:
        - recipient: age1nvhxw9qgra4xuvluqkz3etedv523w7rx632wyh6w3xsc6uh84cps0h0jka
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOckZYVDVyN2ZQUkhWYkFW
            N2xrU2xKenhqWVlaOWxuNXBGZ0k0cDJTTVZ3CmlQR2dkUFV1Nk5TNi9kakgrRytn
            cWVHWHNrS0x0a2pGU3BvWXBYandWY2sKLS0tIE9BZW1WTy9HTkdnQlVhWXlXTXJt
            V1VOcWVMVDh5aXJnZC9xKytMNkZzcDAK8IK+Bu1RZkiXzzslSRLG+VU2/EsZD8Kv
            8iCg1nhnHPoM07Ab0lGE7EOm7U3tbSsP/Y5Y465HQVpg3/CR3MbrWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-03T12:56:26Z"
    mac: ENC[AES256_GCM,data:YwlmkScmflZL8YNb/NJbCZpfo9HXM7D1lGzIZcNu9Pk/TLbBBn4mwAKeltucrqkhtSMPBy96972oIbkcwh4OebfDZp7gCWEEldOeKKnSPaL6qrKqdrMdvCTp2oAY4QEJscM/mwxxo7GoGEqrAh71jfYtqnX5R/FnpfDPLAcFMMs=,iv:WBHV0IAuMEk4/McovjPcN7bN01V982IjO2qb8wlrjog=,tag:9nguYBfGFKm1s5YGQUVsOA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
