apiVersion: v1
kind: Secret
metadata:
  name: furfriend-finder-app-secret
  namespace: furfriend-finder
type: Opaque
stringData:
  DATABASE_URL: postgres://furfriend:REPLACE_WITH_PASSWORD@furfriend-finder-postgresql:5432/furfriend_finder
  GEOCODING_API_KEY: REPLACE_WITH_GEOCODING_API_KEY
  CHANNEL_SECRET: REPLACE_WITH_LINE_CHANNEL_SECRET
  CHANNEL_ACCESS_TOKEN: REPLACE_WITH_LINE_CHANNEL_ACCESS_TOKEN
  ADMIN_API_KEY: REPLACE_WITH_ADMIN_API_KEY
  SMTP_HOST: REPLACE_WITH_SMTP_HOST
  SMTP_PORT: "587"
  SMTP_SECURE: "false"
  SMTP_USER: REPLACE_WITH_SMTP_USER
  SMTP_PASSWORD: REPLACE_WITH_SMTP_PASSWORD
  SMTP_SENT_FROM: REPLACE_WITH_SMTP_SENT_FROM
---
apiVersion: v1
kind: Secret
metadata:
  name: furfriend-finder-postgres-secret
  namespace: furfriend-finder
type: Opaque
stringData:
  POSTGRES_PASSWORD: REPLACE_WITH_POSTGRES_PASSWORD
